### ISSUE TITLE
No autosave of inswapper output only initial Fooocus generated image

### ISSUE THREAD

**Issue by MorkyBork** [machineminded/Fooocus-inswapper#1]
**Describe the problem**
The inswapper generated images are not autosaved in the outputs folder only the initial image generated by Fooocus so have to manually save the inswapper version. 

This might be intended behaviour but is it possible to save the image only after inswapper has been used or save both images?

**Comment by Rondalter** [comment]
solution: 
archive face_swap.py

add 

line 4 
-> import random

line 48

--> random_number = random.randint(1000, 9999)
      nameresult=(f'/content/Fooocus-inswapper/outputs/result{random_number}.png')
      result_image.save(nameresult)


This creates a resultxxx.png file in the outputs folder

**Comment by machineminded** [comment]
Hey guys, I noticed in my particular case, it was saving them to a different directory:

#### **`config.txt`**
``` json
{
  ... some configuration here ...
  "path_outputs": "E:\\github\\Fooocus\\outputs" 👈
}

needed to be updated to

#### **`config.txt`**
``` json
{
  ... some configuration here ...
  "path_outputs": "E:\\github\\Fooocus-inswapper\\outputs" 👈
}
```

Can you guys check that your `config.txt` has the correct directory?

cc: @Rondalter  @MorkyBork

**Comment by MorkyBork** [comment]
@machineminded Yeh the config is definitely pointing to the correct place as the initially generated images are saving just not the face swapped ones checked and it's pointing to the correct place

@Rondalter This gave me enough to get a crude version working. Have to append       
      nameresult=nameresult.replace(':', '')
   before the save to give it a windows acceptable file name as the colons from datetime won't save and remove the path. This generates a file save with the date and time in the main directory. The path issue might just be a different setup between us so might just need some tweaking but it is saving the reworked images so thanks.

**Comment by machineminded** [comment]
Thanks for the response @MorkyBork  - I will try to reproduce this on my end.  I am seeing output images in my `outputs` folder under the current date.

**Comment by MorkyBork** [comment]
@machineminded I do get an output in the outputs folder but only of the pre face swapped images rather than the inswapper outputs so effectively the output that is saved is what I would get with just Fooocus. I might do a fresh install and see if it helps.

**Comment by machineminded** [comment]
> @machineminded I do get an output in the outputs folder but only of the pre face swapped images rather than the inswapper outputs so effectively the output that is saved is what I would get with just Fooocus. I might do a fresh install and see if it helps.

Yep - you're right.  I see what you mean now.

**Comment by machineminded** [comment]
> @machineminded I do get an output in the outputs folder but only of the pre face swapped images rather than the inswapper outputs so effectively the output that is saved is what I would get with just Fooocus. I might do a fresh install and see if it helps.

Can you pull the latest from `main`?  It should be resolved now.

**Comment by MorkyBork** [comment]
Nuked it all and pulled the latest and I get a failure with the traceback below. Went back to the old async_worker.py to check my install and that works fine outside the saving issue.

```
Replacing faces in target image from the left to the right by order
Traceback (most recent call last):
  File "C:\Users\mork\Fooocus-inswapper\modules\async_worker.py", line 835, in worker
    handler(task)
  File "C:\Users\mork\Fooocus-inswapper\venv\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mork\Fooocus-inswapper\venv\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mork\Fooocus-inswapper\modules\async_worker.py", line 814, in handler
    log(x, d)
  File "C:\Users\mork\Fooocus-inswapper\modules\private_logger.py", line 27, in log
    Image.fromarray(img).save(local_temp_filename)
    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mork\Fooocus-inswapper\venv\Lib\site-packages\PIL\Image.py", line 2974, in fromarray
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mork\Fooocus-inswapper\venv\Lib\site-packages\PIL\Image.py", line 2901, in frombuffer
    return frombytes(mode, size, data, decoder_name, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mork\Fooocus-inswapper\venv\Lib\site-packages\PIL\Image.py", line 2843, in frombytes
    im.frombytes(data, decoder_name, args)
  File "C:\Users\mork\Fooocus-inswapper\venv\Lib\site-packages\PIL\Image.py", line 795, in frombytes
    s = d.decode(data)
        ^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'Image'
```

**Comment by machineminded** [comment]
I'm running a fresh install now to see what might be going on.

**Comment by machineminded** [comment]
Ah okay, I see the issue now.  I forgot to check in some changes to the `private_logger.py`.  Perform a git pull again on main and try it.

**Comment by machineminded** [comment]
Now I really want the filenames to be correct in Chrome instead of just `image.png`!

**Comment by MorkyBork** [comment]
Yep all working and saving the outputs, thanks.
