### ISSUE TITLE
stuck at "Waiting for task to start ..."

### ISSUE THREAD

**Issue by Amit30swgoh** [machineminded/Fooocus-inswapper#22]
**Read Troubleshoot**

[x] I confirm that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) guide before making this issue.

**Describe the problem**

**Full Console Log**
Paste the **full** console log here. You will make our job easier if you give a **full** log.

![image](https://github.com/machineminded/Fooocus-inswapper/assets/42430868/24e2398b-c94e-471d-bd30-de1ec12f8fc0)

using:

!pip install pygit2==1.12.2
%cd /content
!git clone https://github.com/machineminded/Fooocus-inswapper.git
!git checkout feature/issue-21-mult-target-insightface
%cd /content/Fooocus-inswapper
!chmod +x configure-colab.sh
!/content/Fooocus-inswapper/configure-colab.sh
# %pip install -r requirements_versions.txt

!python launch.py --theme dark --share --disable-offload-from-vram --always-high-vram --all-in-fp16

**Comment by Amit30swgoh** [comment]
Can we talk on discord please?

**Comment by machineminded** [comment]
@Amit30swgoh  Sure - you can reach me under the same username there.  I am aware that the Colab is not working.

**Comment by machineminded** [comment]
Closed as duplicate.  We will get the Colab working soon.

https://github.com/machineminded/Fooocus-inswapper/issues/6

**Comment by machineminded** [comment]
@Amit30swgoh  I have pinned the issue so I will switch focus to this since it appears many users want this now.

**Comment by Amit30swgoh** [comment]
Ty friend
