### ISSUE TITLE
Feature: Build a run.bat file when configure.bat is completed successfully  

### ISSUE THREAD

**Issue by ujl123** [machineminded/Fooocus-inswapper#23]
**Is your feature request related to a problem? Please describe.**

Instead of having users having to write a command each time they want to run it or create their own bat file, it should be autogenerated when configure.bat is ran successfully 

**Describe the idea you'd like**

create a run.bat file with the follow inside. Unsure if that will work for all OS though as I only have experience with windows
`.\venv\Scripts\activate && python launch.py`

**Comment by machineminded** [comment]
Thanks for the report.  I have added `run.bat` and `run.sh`.  They will accept the [main repository's command line arguments](https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#all-cmd-flags).
