### ISSUE TITLE
History Log does not work

### ISSUE THREAD

**Issue by ujl123** [machineminded/Fooocus-inswapper#24]
**Read Troubleshoot**

[x] I confirm that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) guide before making this issue.

**Describe the problem**
Windows 10
Firefox/Chrome

When using History Log (Advanced -> History Log), the browser returns this error instead `{"detail":"File not allowed: //desk1/G/bit/SD/images/2024-02-19/log.html."}`

Couple of caveats. 
1. The link is to a mapped drive, but a valid drive. If I use `file://///desk1/G/bit/SD/images/2024-02-19/log.html` this will open the log html file.
2. In my installation folder, I have used a symlink to file://///desk1/G/bit/SD/images/  instead of `C:\Fooocus inswapper\Fooocus-inswapper`

Unsure if either of the above caused the issue, or if this is prevalent on a normal install that didn't muck with the output folder.

**Full Console Log**

browser error (chrome and firefox)
{"detail":"File not allowed: //desk1/G/bit/SD/images/2024-02-19/log.html."}

**Comment by machineminded** [comment]
I've noticed instances where sometimes it works, and other times it doesn't work.  I'm not sure what the root cause is, but will try to dig into it.

**Comment by ujl123** [comment]
It looks like the link for history log goes to : 
http://127.0.0.1:7865/file=//desk1/G/bit/SD/images/2024-02-19/log.html

Should it not just go to 
file://<path-to-log-file>  or file:////desk1/G/bit/SD/images/2024-02-19/log.html ?

**Comment by machineminded** [comment]
Can you provide steps to reproduce?  Right now the logger seems to be working.  Is the inswapper feature active or is it disabled?

**Comment by ujl123** [comment]
Hey @machineminded rereading my post I realized I might not been clear. The "History log" hyperlink does not click to a working link.

It clicks out to this link below, returns "file not allowed" . I suspect it's because it's a UNC path rather than a mapped drive. Again, I'm not sure if it being a network drive is causing this issue or not.

Let me know if there's any other steps you need me to follow for clarity. 

127.0.0.1:7865/file=//desk1/G/bit/SD/images/2024-02-19/log.html

![image](https://github.com/machineminded/Fooocus-inswapper/assets/13132548/65ab9bd9-b1f9-4b17-99d5-84710dda0a41)

![image](https://github.com/machineminded/Fooocus-inswapper/assets/13132548/77b75efa-11dd-43b4-9806-7f059b934f11)

**Comment by ujl123** [comment]
Also, to add, the log itself does work, it's just that the link cannot open it

![image](https://github.com/machineminded/Fooocus-inswapper/assets/13132548/b2b80ea1-4fbc-4cbf-9e63-c68bf82694ab)

**Comment by machineminded** [comment]
Got it - that would probably be an issue with the base Fooocus repo, but I am happy to investigate the issue.

**Comment by ujl123** [comment]
Didn't even occur to me to look upstream. I haven't used based fooocus for a while and I didn't think it had log history. I also see a ticket on the upstream regarding this. This is good to close https://github.com/lllyasviel/Fooocus/issues/2209
