### ISSUE TITLE
InstantID - "Waiting for task to start ..."

### ISSUE THREAD

**Issue by tailgunnerx** [machineminded/Fooocus-inswapper#27]
Using InstandID for the first time, just getting "Waiting for task to start ..." and don't think anything else is happening.

**Comment by machineminded** [comment]
Are you running in colab?

**Comment by machineminded** [comment]
Are there any errors in the log or is it just hanging on `Waiting for task to start`?  What hardware are you running it on?  It has a very high VRAM requirement.

**Comment by tailgunnerx** [comment]
4070
12700k
32 gb ram

No errors in the console. Is it just taking a long time to load maybe?

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by machineminded** [comment]
It seems like others are having an issue using it on 12GB cards:

https://github.com/InstantID/InstantID/issues/61

I am going to experiment with offloading to bring down the requirement a bit.  Even right now with moving FaceAnalysis to CPU, it is using 20GB of VRAM.

**Comment by Divyanshuchauhan8** [comment]
earlier it's working fine now having same issue waiting for task in colab

**Comment by machineminded** [comment]
Are you trying to use this on Colab free tier?  If so, I don't think it will work because Google has blocked this process.
