### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by tailgunnerx** [machineminded/Fooocus-inswapper#8]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

Hello MachineMinded, I'm having some issues getting everything installed with this.
Can you tell the correct initial install procedure as far as which python/bat scripts to run and I will let you know where I'm getting stuck.

**Comment by machineminded** [comment]
Should be able to just run configure.bat for Windows and configure.sh for Linux.  I will perform a fresh clone and run on my end.  Can you post any errors or stacktrace you have?

**Comment by tailgunnerx** [comment]
configure.bat I'm getting the C++ not installed error (installing it now) and it cannot build the wheels for insightface. When the "writing web request" finishes then the .bat closes.

**Comment by tailgunnerx** [comment]
which version of tb-nightly is required?

**Comment by machineminded** [comment]
> configure.bat I'm getting the C++ not installed error (installing it now) and it cannot build the wheels for insightface. When the "writing web request" finishes then the .bat closes. Which is the correct one to run the start the app? Build_Lanucher.py?

You can start the app with `python launch.py` after activating your python virtual environment.

> which version of tb-nightly is required?

This appears to be a nightly build of tensorboard.  Admittedly, I copied these requirements from [haofanwang's inswapper](https://github.com/haofanwang/inswapper) repository.  The latest version here should be fine, I think.

I am going to run a fresh install now and see if I run into similar issues.

**Comment by tailgunnerx** [comment]
Thanks for checking. Will wait for your findings as well.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by machineminded** [comment]
Please accept my apologies about not including instructions for the C++ runtime.  I'm not sure of this requirement - I already have this installed, though I'm not sure which version is required:

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

My guess is latest from here should suffice, though I appear to have multiple versions installed on my PC.

**Comment by machineminded** [comment]
@tailgunnerx After `configure.bat` finishes, the window may close depending how you launched it.  If you double-clicked the `configure.bat` and it opened a new window, the window will close after `Writing Web Request` completes.  If you executed `configure.bat` from within an existing command prompt, the window would not close.

Based on your experience it seems the install was successful.  Are you able to launch the app by first activating the `venv` with `.\venv\Scripts\activate` then running `python launch.py`?

**Comment by tailgunnerx** [comment]
The default installation for the "Desktop development with C++" was enough to curb the error.

I get this error from the VENV

> (venv) C:\Fooocus-inswapper>python launch.py
> [System ARGV] ['launch.py']
> Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD(venv) C:\Fooocus-inswapper>python launch.py
> [System ARGV] ['launch.py']
> Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
> Fooocus version: 2.1.864
> Version mismatch for tb-nightly: Installed version 2.16.0a20240207 does not meet requirement tb-nightly
> Installing requirements64)]
> Fooocus version: 2.1.864
> Version mismatch for tb-nightly: Installed version 2.16.0a20240207 does not meet requirement tb-nightly
> Installing requirements

**Comment by machineminded** [comment]
I think this appears to be a warning.  Note that I have the same output below.  I don't think any action is necessary for now.  Do you see a URL after some time similar to how my log looks below?

```
(venv) E:\github\Fooocus-inswapper>python launch.py
[System ARGV] ['launch.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.864
Version mismatch for tb-nightly: Installed version 2.16.0a20240109 does not meet requirement tb-nightly
Installing requirements
Total VRAM 24576 MB, total RAM 49078 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
Base model loaded: E:\github\stable-diffusion-webui\models\Stable-diffusion\sdxl\juggernautXL_v8Rundiffusion.safetensorsRequest to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [E:\github\stable-diffusion-webui\models\Stable-diffusion\sdxl\juggernautXL_v8Rundiffusion.safetensors].
Loaded LoRA [E:\github\stable-diffusion-webui\models\Lora\sd_xl_offset_example-lora_1.0.safetensors] for UNet [E:\github\stable-diffusion-webui\models\Stable-diffusion\sdxl\juggernautXL_v8Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
E:\github\Fooocus-inswapper\venv\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.81 seconds
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
```

**Comment by tailgunnerx** [comment]
No it's a bit different.

> (venv) C:\Fooocus-inswapper>python launch.py
> [System ARGV] ['launch.py']
> Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
> Fooocus version: 2.1.864
> Version mismatch for tb-nightly: Installed version 2.16.0a20240207 does not meet requirement tb-nightly
> Installing requirements
> Exception in thread Thread-4 (worker):
> Traceback (most recent call last):
>   File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "C:\Python310\lib\threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Fooocus-inswapper\modules\async_worker.py", line 25, in worker
>     import modules.default_pipeline as pipeline
>   File "C:\Fooocus-inswapper\modules\default_pipeline.py", line 1, in <module>
>     import modules.core as core
>   File "C:\Fooocus-inswapper\modules\core.py", line 1, in <module>
>     from modules.patch import patch_all
>   File "C:\Fooocus-inswapper\modules\patch.py", line 5, in <module>
>     import ldm_patched.modules.model_base
>   File "C:\Fooocus-inswapper\ldm_patched\modules\model_base.py", line 2, in <module>
>     from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
>   File "C:\Fooocus-inswapper\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 15, in <module>
>     from ..attention import SpatialTransformer, SpatialVideoTransformer, default
>   File "C:\Fooocus-inswapper\ldm_patched\ldm\modules\attention.py", line 9, in <module>
>     from .sub_quadratic_attention import efficient_dot_product_attention
>   File "C:\Fooocus-inswapper\ldm_patched\ldm\modules\sub_quadratic_attention.py", line 27, in <module>
>     from ldm_patched.modules import model_management
>   File "C:\Fooocus-inswapper\ldm_patched\modules\model_management.py", line 118, in <module>
>     total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
>   File "C:\Fooocus-inswapper\ldm_patched\modules\model_management.py", line 87, in get_torch_device
>     return torch.device(torch.cuda.current_device())
>   File "C:\Fooocus-inswapper\venv\lib\site-packages\torch\cuda\__init__.py", line 674, in current_device
>     _lazy_init()
>   File "C:\Fooocus-inswapper\venv\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
>     raise AssertionError("Torch not compiled with CUDA enabled")
> AssertionError: Torch not compiled with CUDA enabled
> Traceback (most recent call last):
>   File "C:\Fooocus-inswapper\launch.py", line 126, in <module>
>     from webui import *
>   File "C:\Fooocus-inswapper\webui.py", line 18, in <module>
>     import modules.pm as pm
>   File "C:\Fooocus-inswapper\modules\pm.py", line 11, in <module>
>     import modules.default_pipeline as pipeline
>   File "C:\Fooocus-inswapper\modules\default_pipeline.py", line 1, in <module>
>     import modules.core as core
>   File "C:\Fooocus-inswapper\modules\core.py", line 1, in <module>
>     from modules.patch import patch_all
>   File "C:\Fooocus-inswapper\modules\patch.py", line 5, in <module>
>     import ldm_patched.modules.model_base
>   File "C:\Fooocus-inswapper\ldm_patched\modules\model_base.py", line 2, in <module>
>     from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
>   File "C:\Fooocus-inswapper\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 15, in <module>
>     from ..attention import SpatialTransformer, SpatialVideoTransformer, default
>   File "C:\Fooocus-inswapper\ldm_patched\ldm\modules\attention.py", line 9, in <module>
>     from .sub_quadratic_attention import efficient_dot_product_attention
>   File "C:\Fooocus-inswapper\ldm_patched\ldm\modules\sub_quadratic_attention.py", line 27, in <module>
>     from ldm_patched.modules import model_management
>   File "C:\Fooocus-inswapper\ldm_patched\modules\model_management.py", line 118, in <module>
>     total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
>   File "C:\Fooocus-inswapper\ldm_patched\modules\model_management.py", line 87, in get_torch_device
>     return torch.device(torch.cuda.current_device())
>   File "C:\Fooocus-inswapper\venv\lib\site-packages\torch\cuda\__init__.py", line 674, in current_device
>     _lazy_init()
>   File "C:\Fooocus-inswapper\venv\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
>     raise AssertionError("Torch not compiled with CUDA enabled")
> AssertionError: Torch not compiled with CUDA enabled

**Comment by machineminded** [comment]
Oh, I actually ran into this as well.  The error indicates that the installed torch does not run on GPU.

Do you happen to know which version of CUDA you have installed on your system?  I am using CUDA 11.8, so I installed the necessary torch installation.  I need to get this added to the documentation:

```
pip install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```

This will upgrade to the latest pytorch, torchvision and torchaudio.  Note the URL indicates CUDA runtime 11.8, if you have a different version then we will have to change that value.

**Comment by tailgunnerx** [comment]
Which version is required?

**Comment by machineminded** [comment]
I would think CUDA 10+ would work.  I have only tested with 11.8.

**Comment by machineminded** [comment]
You can get latest here:

https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64

Or CUDA 11.8 here:

https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Windows&target_arch=x86_64

**Comment by tailgunnerx** [comment]
If my understanding is correct pytorch is only supported on 11.8 and 12.1 right? Is Torchvision the same as pytorch I'm assuming?

**Comment by machineminded** [comment]
> If my understanding is correct pytorch is only supported on 11.8 and 12.1 right? Is Torchvision the same as pytorch I'm assuming?

Not entirely - if you were to use say, CUDA 10.2, you would need pytorch 1.12.1 [per the documentation here](https://pytorch.org/get-started/previous-versions/).

torch and torchvision are separate packages, though they are usually installed together.  torch would be PyTorch, and torchvision is a separate package.

**Comment by tailgunnerx** [comment]
are you able to confirm all the versions in the requirements_versions are correct? or that you were able to run with the requirements

**Comment by tailgunnerx** [comment]
This is where I'm at:

> C:\Fooocus-inswapper>python launch.py
> [System ARGV] ['launch.py']
> Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
> Fooocus version: 2.1.864
> Version mismatch for protobuf: Installed version 3.20.3 does not meet requirement protobuf>=4.23.2
> Installing requirements
> Exception in thread Thread-4 (worker):
> Traceback (most recent call last):
>   File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "C:\Python310\lib\threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Fooocus-inswapper\modules\async_worker.py", line 25, in worker
>     import modules.default_pipeline as pipeline
>   File "C:\Fooocus-inswapper\modules\default_pipeline.py", line 1, in <module>
>     import modules.core as core
>   File "C:\Fooocus-inswapper\modules\core.py", line 1, in <module>
>     from modules.patch import patch_all
>   File "C:\Fooocus-inswapper\modules\patch.py", line 5, in <module>
>     import ldm_patched.modules.model_base
>   File "C:\Fooocus-inswapper\ldm_patched\modules\model_base.py", line 2, in <module>
>     from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
>   File "C:\Fooocus-inswapper\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 15, in <module>
>     from ..attention import SpatialTransformer, SpatialVideoTransformer, default
>   File "C:\Fooocus-inswapper\ldm_patched\ldm\modules\attention.py", line 9, in <module>
>     from .sub_quadratic_attention import efficient_dot_product_attention
>   File "C:\Fooocus-inswapper\ldm_patched\ldm\modules\sub_quadratic_attention.py", line 27, in <module>
>     from ldm_patched.modules import model_management
>   File "C:\Fooocus-inswapper\ldm_patched\modules\model_management.py", line 118, in <module>
>     total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
>   File "C:\Fooocus-inswapper\ldm_patched\modules\model_management.py", line 87, in get_torch_device
>     return torch.device(torch.cuda.current_device())
>   File "C:\Python310\lib\site-packages\torch\cuda\__init__.py", line 674, in current_device
>     _lazy_init()
>   File "C:\Python310\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
>     raise AssertionError("Torch not compiled with CUDA enabled")
> AssertionError: Torch not compiled with CUDA enabled
> Traceback (most recent call last):
>   File "C:\Python310\lib\site-packages\tensorboard\compat\__init__.py", line 42, in tf
>     from tensorboard.compat import notf  # noqa: F401
> ImportError: cannot import name 'notf' from 'tensorboard.compat' (C:\Python310\lib\site-packages\tensorboard\compat\__init__.py)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1364, in _get_module
>     return importlib.import_module("." + module_name, self.__name__)
>   File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "C:\Python310\lib\site-packages\transformers\generation\utils.py", line 93, in <module>
>     from accelerate.hooks import AlignDevicesHook, add_hook_to_module
>   File "C:\Python310\lib\site-packages\accelerate\__init__.py", line 3, in <module>
>     from .accelerator import Accelerator
>   File "C:\Python310\lib\site-packages\accelerate\accelerator.py", line 41, in <module>
>     from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
>   File "C:\Python310\lib\site-packages\accelerate\tracking.py", line 43, in <module>
>     from torch.utils import tensorboard
>   File "C:\Python310\lib\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>
>     from .writer import FileWriter, SummaryWriter  # noqa: F401
>   File "C:\Python310\lib\site-packages\torch\utils\tensorboard\writer.py", line 16, in <module>
>     from ._embedding import (
>   File "C:\Python310\lib\site-packages\torch\utils\tensorboard\_embedding.py", line 9, in <module>
>     _HAS_GFILE_JOIN = hasattr(tf.io.gfile, "join")
>   File "C:\Python310\lib\site-packages\tensorboard\lazy.py", line 65, in __getattr__
>     return getattr(load_once(self), attr_name)
>   File "C:\Python310\lib\site-packages\tensorboard\lazy.py", line 97, in wrapper
>     cache[arg] = f(arg)
>   File "C:\Python310\lib\site-packages\tensorboard\lazy.py", line 50, in load_once
>     module = load_fn()
>   File "C:\Python310\lib\site-packages\tensorboard\compat\__init__.py", line 45, in tf
>     import tensorflow
>   File "C:\Python310\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
>     from tensorflow.python.tools import module_util as _module_util
>   File "C:\Python310\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
>     from tensorflow.python.eager import context
>   File "C:\Python310\lib\site-packages\tensorflow\python\eager\context.py", line 29, in <module>
>     from tensorflow.core.framework import function_pb2
>   File "C:\Python310\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
>     from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
>   File "C:\Python310\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
>     from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
>   File "C:\Python310\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
>     from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
>   File "C:\Python310\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
>     from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
>   File "C:\Python310\lib\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
>     _descriptor.FieldDescriptor(
>   File "C:\Python310\lib\site-packages\google\protobuf\descriptor.py", line 553, in __new__
>     _message.Message._CheckCalledFromGeneratedFile()
> TypeError: Descriptors cannot be created directly.
> If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
> If you cannot immediately regenerate your protos, some other possible workarounds are:
>  1. Downgrade the protobuf package to 3.20.x or lower.
>  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
> 
> More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Fooocus-inswapper\launch.py", line 126, in <module>
>     from webui import *
>   File "C:\Fooocus-inswapper\webui.py", line 18, in <module>
>     import modules.pm as pm
>   File "C:\Fooocus-inswapper\modules\pm.py", line 8, in <module>
>     from photomaker import PhotoMakerStableDiffusionXLPipeline
>   File "C:\Fooocus-inswapper\photomaker\__init__.py", line 1, in <module>
>     from .model import PhotoMakerIDEncoder
>   File "C:\Fooocus-inswapper\photomaker\model.py", line 6, in <module>
>     from transformers.models.clip.modeling_clip import CLIPVisionModelWithProjection
>   File "C:\Python310\lib\site-packages\transformers\models\clip\modeling_clip.py", line 28, in <module>
>     from ...modeling_utils import PreTrainedModel
>   File "C:\Python310\lib\site-packages\transformers\modeling_utils.py", line 44, in <module>
>     from .generation import GenerationConfig, GenerationMixin
>   File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
>   File "C:\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1354, in __getattr__
>     module = self._get_module(self._class_to_module[name])
>   File "C:\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1366, in _get_module
>     raise RuntimeError(
> RuntimeError: Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
> Descriptors cannot be created directly.
> If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
> If you cannot immediately regenerate your protos, some other possible workarounds are:
>  1. Downgrade the protobuf package to 3.20.x or lower.
>  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

**Comment by machineminded** [comment]
For some reason an older version of protobuf was installed.  My `pip show protobuf` shows version 4.25.1:

```
(venv) PS E:\github\Fooocus-inswapper> pip show protobuf
Name: protobuf
Version: 4.25.1
Summary: 
Home-page: https://developers.google.com/protocol-buffers/  
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
License: 3-Clause BSD License
Location: e:\github\fooocus-inswapper\venv\lib\site-packages
Requires: 
Required-by: onnx, onnxruntime, tb-nightly
```

Let's try

```
pip install --upgrade protobuf==4.25.1
```

And go from there.  Worse comes to worse, we could always blow away the venv and re-create it from scratch.  Sometimes that solves some issues.

**Comment by tailgunnerx** [comment]
can you list me your pytorch versions for:

> torch
> torchvision
> torchaudio

**Comment by machineminded** [comment]
> can you list me your pytorch versions (in the env) for:
> 
> > torch
> > torchvision
> > torchaudio

```
(venv) PS E:\github\Fooocus-inswapper> pip show torch torchvision torchaudio
Name: torch
Version: 2.2.0+cu118
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: e:\github\fooocus-inswapper\venv\lib\site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: accelerate, controlnet-aux, facexlib, lpips, peft, pytorch-lightning, timm, torchaudio, torchmetrics, torchsde, torchvision
---
Name: torchvision
Version: 0.17.0+cu118
Summary: image and video datasets and models for torch deep learning
Home-page: https://github.com/pytorch/vision
Author: PyTorch Core Team
Author-email: soumith@pytorch.org
License: BSD
Location: e:\github\fooocus-inswapper\venv\lib\site-packages
Requires: numpy, pillow, requests, torch
Required-by: controlnet-aux, facexlib, lpips, timm
---
Name: torchaudio
Version: 2.2.0+cu118
Summary: An audio package for PyTorch
Home-page: https://github.com/pytorch/audio
Author: Soumith Chintala, David Pollack, Sean Naren, Peter Goldsborough, Moto Hira, Caroline Chen, Jeff Hwang, Zhaoheng Ni, Xiaohui Zhang
Author-email: soumith@pytorch.org
License:
Location: e:\github\fooocus-inswapper\venv\lib\site-packages
Requires: torch
Required-by:
```

**Comment by igrikum** [comment]
Can anyone give me a normal link with working focus and PhotoMaker?

**Comment by tailgunnerx** [comment]
@machineminded 
Ok the issue is whenever I run launch.py it's downgrading my torch/torchvision versions... but audio stays the same...

> Name: torch
> Version: 2.0.1
> 
> Name: torchvision
> Version: 0.15.2
> 
> Name: torchaudio
> Version: 2.2.0+cu118

**Comment by machineminded** [comment]
What is the error now when you run?

**Comment by tailgunnerx** [comment]
the same as before

**Comment by machineminded** [comment]
The protobuf error?

**Comment by tailgunnerx** [comment]
that and 

> Torch not compiled with CUDA

**Comment by tailgunnerx** [comment]
is launch.py changing the torch version?

**Comment by machineminded** [comment]
Yeah - this is default behavior from the main repo.  It's also using CUDA 12.1.  Can you try going into `launch.py` and removing or commenting out lines 32 through 41?  After you have saved the change, please run your pip install command for torch, then run the launch.py.

Note the commented lines:
```python
    # torch_index_url = os.environ.get('TORCH_INDEX_URL', "https://download.pytorch.org/whl/cu121")
    # torch_command = os.environ.get('TORCH_COMMAND',
    #                                f"pip install torch==2.1.0 torchvision==0.16.0 --extra-index-url {torch_index_url}")
    # requirements_file = os.environ.get('REQS_FILE', "requirements_versions.txt")

    # print(f"Python {sys.version}")
    # print(f"Fooocus version: {fooocus_version.version}")

    # if REINSTALL_ALL or not is_installed("torch") or not is_installed("torchvision"):
    #     run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
```

**Comment by tailgunnerx** [comment]
C:\Fooocus-inswapper-main>python launch.py
[System ARGV] ['launch.py']
Traceback (most recent call last):
  File "C:\Fooocus-inswapper-main\launch.py", line 53, in <module>
    prepare_environment()
  File "C:\Fooocus-inswapper-main\launch.py", line 34, in prepare_environment
    if REINSTALL_ALL or not requirements_met(requirements_file):
NameError: name 'requirements_file' is not defined. Did you mean: 'requirements_met'?

**Comment by tailgunnerx** [comment]
alright getting somewhere I think

**Comment by tailgunnerx** [comment]
again had to downgrade 

> pip install protobuf==3.19.0

I got the web UI up now, we'll see if everything works

**Comment by machineminded** [comment]
Let's comment out lines 58 and 59 too:

```python
    # if REINSTALL_ALL or not requirements_met(requirements_file):
    #     run_pip(f"install -r \"{requirements_file}\"", "requirements")
```

**Comment by tailgunnerx** [comment]
> Let's comment out lines 58 and 59 too:
> 
> ```python
>     # if REINSTALL_ALL or not requirements_met(requirements_file):
>     #     run_pip(f"install -r \"{requirements_file}\"", "requirements")
> ```

yeah sorry missed it the first time

**Comment by tailgunnerx** [comment]
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (C:\Python310\lib\site-packages\google\protobuf\internal\__init__.py)

**Comment by tailgunnerx** [comment]
upgraded back to your suggestion:

> pip install --upgrade protobuf==4.25.1

then getting:

>  1. Downgrade the protobuf package to 3.20.x or lower.
>  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

**Comment by tailgunnerx** [comment]
went down to 

> 3.20.3

and appears to be working now

**Comment by machineminded** [comment]
> went down to
> 
> > 3.20.3
> 
> and appears to be working now

That great that it is working now 🎉🎉.  I am not sure why it wants such a low version.  I was going to suggest starting over with the `venv` and rebuild it, but maybe we'll do that if something comes up.

**Comment by tailgunnerx** [comment]
> > went down to
> > > 3.20.3
> > 
> > 
> > and appears to be working now
> 
> That great that it is working now 🎉🎉. I am not sure why it wants such a low version. I was going to suggest starting over with the `venv` and rebuild it, but maybe we'll do that if something comes up.

I did start over after you mentioned it.

**Comment by tailgunnerx** [comment]
> > > went down to
> > > > 3.20.3
> > > 
> > > 
> > > and appears to be working now
> > 
> > 
> > That great that it is working now 🎉🎉. I am not sure why it wants such a low version. I was going to suggest starting over with the `venv` and rebuild it, but maybe we'll do that if something comes up.
> 
> I did start over after you mentioned it.

basically to sum it all up, the launch.py was downgrading the torch versions and photobuf version was incorrect

**Comment by tailgunnerx** [comment]
there was a lot of learning on my end as I don't do this a lot lol

**Comment by machineminded** [comment]
Good work!  I will consider modifying the launch.py to not perform those operations.

**Comment by tailgunnerx** [comment]
Alright I should probably start a new thread for the new errors lol

**Comment by machineminded** [comment]
What errors are you seeing?

**Comment by tailgunnerx** [comment]
> What errors are you seeing?

I started new threads for them so easier to track for you

**Comment by tailgunnerx** [comment]
Initial setup:
run **configure.bat** (make sure there's 0 errors)
then run `launch.py` to start application
