### ISSUE TITLE
"No module named basicsr"

### ISSUE THREAD

**Issue by tailgunnerx** [machineminded/Fooocus-inswapper#9]
When using **InSwapper** for the first time:

**"Target Image Index" set to -1**

```
**ModuleNotFoundError: No module named 'basicsr'****
```
### Per ChatGPT4:

> The error message you're encountering, ModuleNotFoundError: No module named 'basicsr', indicates that the Python environment you're working in does not have the basicsr module installed, which is required for the execution of your code. The basicsr library is a part of Basic Super-Resolution Toolbox, commonly used for image and video super-resolution tasks.
> 
> To resolve this issue, you need to install the basicsr package. You can usually do this via pip, Python's package manager. Open your terminal or command prompt and activate your Python environment where you're running the code. Then, install basicsr using the following command:
> 

>> bash
> >
> >**pip install basicsr**

> After installation, try running your script again. The ModuleNotFoundError should be resolved, and your code should proceed beyond the point where it was previously failing.
> 
> If you encounter any other ModuleNotFoundError errors for different packages in the future, you can use the same approach to install the missing modules.

**Comment by tailgunnerx** [comment]
I did follow the instructions and install `pip install basicsr` and **it downgraded my torch down to 2.0.1**. 

I installed the correct torch's again and launched **launch.py** and started up fine

Ran **InSwapper** with **-1** and it worked fine (as far as I can tell). Fixed?

**Comment by machineminded** [comment]
To resolve this you should run the xcopy commands in configure.bat.

**Comment by tailgunnerx** [comment]
> To resolve this you should run the xcopy commands in configure.bat.

did it skip this when I ran **configure.bat** the first/only time?

**Comment by tailgunnerx** [comment]
> To resolve this you should run the xcopy commands in configure.bat.

does xcopy need to have quotes around the file path maybe? since it has spaces in the path?

```
xcopy /E /I /Y inswapper\CodeFormer\CodeFormer\basicsr venv\Lib\site-packages\basicsr
xcopy /E /I /Y inswapper\CodeFormer\CodeFormer\facelib venv\Lib\site-packages\facelib
```

**Comment by machineminded** [comment]
Should work without the quotes.  As long as it is run from within the directory the repo was checked out.

**Comment by tailgunnerx** [comment]
> Should work without the quotes. As long as it is run from within the directory the repo was checked out.

ah I see, they're 2 different dirs

**Comment by tailgunnerx** [comment]
Soluion `pip install basicsr` for the venv
